version: '2'
services:
    PROXY:
        image: igez/haproxy
        restart: always
        volumes:
            - "./haproxy:/etc/haproxy"
        ports:
            - "80:80"
            - "9000:9000"
        container_name: "lb-1"
# Join networks
networks:
    default:
        external:
            name: dev
